/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface resetPassWordWithPassword {
  _csrf?: string;
  password: string;
}

export interface resetPasswordSchema {
  email?: string;
  username?: string;
}

export interface signInUserSchema {
  email?: string;
  password: string;
  username?: string;
}

export interface signUpUserSchema {
  email: string;
  password: string;
  username: string;
}
